config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dday/', include('dday.urls')),
]

dday/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('addEvent/', views.addEvent, name='addEvent'),
    path('addComment/', views.addComment, name='addComment'),
    path('deleteEvent/', views.deleteEvent, name='deleteEvent'),
]
app_name = 'dday'

dday/models.py
from django.db import models

# Create your models here.


class Event(models.Model):
    title = models.CharField(max_length=100)
    offset = models.DateTimeField(verbose_name='기준일')
    pub_date = models.DateTimeField(default='')

    def __str__(self):
        return self.title


class Comment(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    pub_date = models.DateTimeField(default='')

    def __str__(self):
        return self.text

dday/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime, timedelta, timezone
from .models import Event, Comment

# Create your views here.
def index(request):
    list = Event.objects.all().order_by('-pub_date')

    for item in list:
        item.days = -(item.offset - datetime.now(timezone.utc)).days-1
        item.time = item.offset.strftime("%Y-%m-%d")

    context = {'list': list}
    return render(request, "dday/index.html", context)


def addEvent(request):
    e = Event(title=request.POST['title'], offset=request.POST['offset'], pub_date=datetime.now(timezone.utc))
    e.save()
    return HttpResponseRedirect(reverse('dday:index'))


def addComment(request):
    event = get_object_or_404(Event, id=request.POST['id'])
    comment = Comment(event=event, text=request.POST['text'], pub_date=datetime.now(timezone.utc))
    comment.save()
    return HttpResponseRedirect(reverse('dday:index') + '#' + str(event.id))


def deleteEvent(request):
    e = get_object_or_404(Event, id=request.POST['id'])
    e.delete()
    return HttpResponseRedirect(reverse('dday:index'))

dday/templates/dday/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>D-Day</title>
</head>
<body>
    <div style="background-color:rgba(255,255,0,0.7); left:0; top:0; height:100%; width:20rem; position:fixed; padding: 10px; box-sizing: border-box; text-align:center;">
        <p><b>D-day 등록</b></p>
        <form method="post" action="{% url 'dday:addEvent' %}">{% csrf_token %}
            <textarea name="title" style="width:100%; height:20rem; font-size:20px;" required></textarea>
            <input type="date" name="offset" style="width:100%" required>
            <br><br>
            <button type="submit" style="width:100%; height:2rem;">등록하기</button>
        </form>
    </div>

    <div style="margin:0 0 0 21rem;">

        {% if list %}
        {% for item in list %}
        <div style="background-color:AntiqueWhite; box-shadow: 0px 0px 5px red; padding: 10px; margin: 20px 0" id="{{item.id}}">
            <h2 style="margin-Bottom:0; display:inline-block;">{{ item.title }}</h2>
            <p style="display:inline-block;">{{item.time }}</p>
            <form style="display:inline-block; " method="post" action="{% url 'dday:deleteEvent' %}">{% csrf_token %}
                <button type="submit" name="id" value="{{item.id}}" style="display:inline-block; background-color:transparent; border: none;">삭제하기</button>
            </form>
            {% if item.days < 0 %}
            <h1>D{{ item.days }}</h1>
            {% elif item.days == 0 %}
            <h1>D-Day</h1>
            {% else %}
            <h1>D+{{ item.days }}</h1>
            {% endif %}

            <form method="post" action="{% url 'dday:addComment' %}">{% csrf_token %}
                <input type="text" name="text" required>
                <button type="submit" name="id" value="{{item.id}}">댓글 작성</button>
            </form>
            {% for comment in item.comment_set.all %}
                <li>익명 : {{ comment.text }}</li>
            {% endfor %}

        </div>
        {% endfor %}
        {% endif %}

    </div>
</body>
</html>